import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=process.env.PORT||3000;
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'..','public')));
const rules=[
{id:'SQLI-001',name:'Potential SQL Injection',severity:'Critical',confidence:'High',languages:['python','javascript','java','cpp'],source:/(request\.|req\.|input\(|params|query|user(name)?\s*=|argv)/i,sink:/(execute\s*\(|executemany\s*\(|query\s*\(|createStatement\s*\(|raw\s*\()/i,message:'Untrusted input appears to reach a SQL execution sink through string construction.',remediation:'Use parameterized queries or prepared statements.'},
{id:'CMD-001',name:'Potential Command Injection',severity:'Critical',confidence:'High',languages:['python','javascript','java','cpp'],source:/(request\.|req\.|input\(|argv|params|user_input|userInput)/i,sink:/(os\.system\s*\(|subprocess\.(run|Popen|call)\s*\(|child_process\.(exec|execSync)\s*\(|Runtime\.getRuntime\(\)\.exec\s*\()/i,message:'Externally controlled data appears to reach a command execution API.',remediation:'Avoid shell interpretation; use safe argument arrays and strict allowlists.'},
{id:'XSS-001',name:'Potential Cross-Site Scripting',severity:'High',confidence:'Medium',languages:['javascript','html'],source:/(location\.search|location\.hash|req\.query|req\.params|request\.getParameter|userInput)/i,sink:/(innerHTML\s*=|outerHTML\s*=|document\.write\s*\(|insertAdjacentHTML\s*\()/i,message:'User-controlled content appears to reach an HTML sink without visible encoding.',remediation:'Prefer textContent or a trusted sanitizer and encode untrusted HTML.'},
{id:'SECRET-001',name:'Hardcoded Secret',severity:'High',confidence:'High',languages:['python','javascript','java','cpp'],pattern:/(api[_-]?key|secret|password|token|access[_-]?key)\s*[:=]\s*["\'][^"\']{8,}["\']/i,message:'A credential-like value is hardcoded in source code.',remediation:'Move secrets to environment variables or a secret manager and rotate exposed credentials.'},
{id:'CRYPTO-001',name:'Weak Cryptography',severity:'Medium',confidence:'High',languages:['python','javascript','java','cpp'],pattern:/\b(md5|sha1|des|rc4)\b/i,message:'A weak or legacy cryptographic primitive was detected.',remediation:'Use modern approved cryptographic primitives.'},
{id:'DESER-001',name:'Unsafe Deserialization',severity:'High',confidence:'Medium',languages:['python','java'],pattern:/(pickle\.loads?\s*\(|ObjectInputStream\s*\(|readObject\s*\()/i,message:'A deserialization API can be dangerous when input is not fully trusted.',remediation:'Avoid deserializing untrusted data; use safe formats and explicit validation.'},
{id:'PATH-001',name:'Potential Path Traversal',severity:'High',confidence:'Medium',languages:['python','javascript','java'],source:/(request\.|req\.|input\(|params|query|filename|fileName)/i,sink:/(open\s*\(|readFile\s*\(|writeFile\s*\(|FileInputStream\s*\(|FileOutputStream\s*\()/i,message:'Externally influenced path data appears to reach a file operation.',remediation:'Normalize paths and enforce an allowlisted base directory.'}
];
const lineAt=(s,i)=>s.slice(0,i).split('\n').length;
function analyze(code,lang){const out=[];for(const r of rules){if(!r.languages.includes(lang))continue;if(r.pattern){const m=r.pattern.exec(code);if(m)out.push({...r,evidence:[{line:lineAt(code,m.index),text:code.split('\n')[lineAt(code,m.index)-1]?.trim()||''}],trace:['matching code construct',`rule ${r.id}`,'deterministic match']});continue}const sm=r.source.exec(code),km=r.sink.exec(code);if(sm&&km){out.push({...r,evidence:[{line:lineAt(code,sm.index),text:code.split('\n')[lineAt(code,sm.index)-1]?.trim()||'',role:'source'},{line:lineAt(code,km.index),text:code.split('\n')[lineAt(code,km.index)-1]?.trim()||'',role:'sink'}],trace:[`line ${lineAt(code,sm.index)}: source-like input`,'data-flow candidate',`line ${lineAt(code,km.index)}: dangerous sink`,'deterministic rule match']})}}return out.map(({source,sink,pattern,languages,...x})=>x)}
app.post('/api/analyze',(req,res)=>{const {code,language='python'}=req.body||{};if(typeof code!=='string'||!code.trim())return res.status(400).json({error:'Code is required.'});if(code.length>200000)return res.status(413).json({error:'Code is too large.'});const findings=analyze(code,language),c={Critical:0,High:0,Medium:0,Low:0};findings.forEach(f=>c[f.severity]++);res.json({success:true,engine:'SECURECODE-X Deterministic Analyzer',llmUsed:false,externalApiUsed:false,language,analyzedLines:code.split(/\r?\n/).length,findings,summary:{total:findings.length,critical:c.Critical,high:c.High,medium:c.Medium,low:c.Low,status:findings.length?'Issues detected':'No deterministic matches detected'},analyzedAt:new Date().toISOString()})});
app.get('/api/health',(_,res)=>res.json({ok:true,service:'SECURECODE-X'}));app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));app.listen(PORT,()=>console.log(`SECURECODE-X running at http://localhost:${PORT}`));
